name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
  
  jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
	
	steps:
    # Get files from repository    
    - uses: actions/checkout@v2
    # Install NodeJS with current version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
	# Install NPM dependencies
    - run: npm ci
      working-directory: ./backend
    # Run Jest tests
    - run: npm test
      working-directory: ./backend
	  
	build-frontend:
    runs-on: ubuntu-latest

    steps:
    # Get files from repository    
    - uses: actions/checkout@v2
    # Install NodeJS
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    # Install NPM dependencies
    - run: npm ci
      working-directory: ./frontend
    # Generate static files
    - run: npm run build
      working-directory: ./frontend
    # Save static files as artifact
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: frontend-build
        path: ./frontend/dist
        retention-days: 7
